//! Raw FFI bindings to the prebuilt static llama.cpp archives.
//!
//! The bindings are generated by the `static-llama-cpp-rs-builder` release (bindgen) and
//! their path is exported by `build.rs` as `STATIC_LLAMA_BINDINGS`; the static archives are
//! linked there too. This module only re-exports the raw symbols — safe wrappers live in
//! `super`.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unpredictable_function_pointer_comparisons,
    clippy::all
)]

include!(env!("STATIC_LLAMA_BINDINGS"));
